### ISSUE TITLE
Search: results incomplete

### ISSUE THREAD

**Issue by Sterling463** [rackerlabs/solution-docs-homepage#45]
Searching for common terms like 'Google' and 'Amazon Web service' does not get any results. Search results seem to be limited to content in headers and title.

**Comment by robb-romans** [comment]
![image](https://user-images.githubusercontent.com/730187/114926233-b8ecb100-9df5-11eb-9e63-3c3d141d0f2c.png)

**Comment by robb-romans** [comment]
![image](https://user-images.githubusercontent.com/730187/114926301-cb66ea80-9df5-11eb-8e66-46d2c5fcb5d6.png)

**Comment by stephamon** [comment]
Confirming same behavior. Search does not seem to be reading past the first couple header levels.

**Comment by catlook** [comment]
The Cloud Servers Guide has at least four operations about key pairs (create, import, delete, and retrieve).  When I searched for "key pair" however, I got nothing. I think search should go a little deeper.

**Comment by ravivalluri** [comment]
Fixed.
