### ISSUE TITLE
Search: does not find article titles

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/solution-docs-homepage#46]
Looks like search does not find article titles. Do we want to index titles?

![image](https://user-images.githubusercontent.com/730187/114925640-f997fa80-9df4-11eb-9e4e-474ebfc9e92f.png)

**Comment by robb-romans** [comment]
![image](https://user-images.githubusercontent.com/730187/114926480-00733d00-9df6-11eb-92fd-fa567f93c20a.png)

**Comment by ravivalluri** [comment]
Fixed.
